version: '3.7'
services:
    backend:
        build:
            dockerfile: ./docker/Dockerfile
            context: ../
        image: easeat/backend
        container_name: easeat-backend
        env_file:
            - ../.env 
        ports:
            - 80:80